# Generated by Django 5.2 on 2026-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('concert', 'Концерт'), ('theatre', 'Театр'), ('festival', 'Фестиваль'), ('exhibition', 'Выставка')], max_length=50)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('total_tickets', models.IntegerField()),
                ('available_tickets', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
